[package]
name = "knot_language"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
combine = "4.6.6"
indenter = { version = "0.3.3", features = ["std"] }
