flowchart LR
  in(( ))
  out(( ))
  namespace{{Namespace.t}}
  result{{AST.program_t}}

  subgraph knot.resolve
    ImportGraph
    Resolver
  end

  ImportGraph <-.-> Compiler
  Resolver <-.-> Compiler

  subgraph knot.lib
    ModuleTable
  end

  ModuleTable <-.-> Compiler

  subgraph knot.compile
    Compiler
    Parser

    Compiler --> Parser
  end

  in --> |input| namespace --> Compiler
  Parser --> result --> |output| out
