[workspace]

resolver = "2"

members = [
  # "libraries",

  # toolchain
  "toolchain/analyze",
  "toolchain/bin",
  "toolchain/command",
  "toolchain/engine",
  "toolchain/kore",
  "toolchain/language",
  "toolchain/parse",
  # "toolchain/plugin_javascript",

  # generators
  "generator/javascript",

  # platforms
  "platform/web",
]
