verifyConditions:
  - semantic-release-vsce
  - '@semantic-release/github'
prepare:
  path: semantic-release-vsce
  packageVsix: knot-lang.vsix
publish:
  - semantic-release-vsce
  - path: '@semantic-release/github'
    assets: knot-lang.vsix
