export default {
  textAlign: 'textAlign',
  textAlignLast: 'textAlignLast',
  textCombineUpright: 'textCombineUpright',
  textDecoration: 'textDecoration',
  textDecorationColor: 'textDecorationColor',
  textDecorationLine: 'textDecorationLine',
  textDecorationStyle: 'textDecorationStyle',
  textEmphasis: 'textEmphasis',
  textEmphasisColor: 'textEmphasisColor',
  textEmphasisPosition: 'textEmphasisPosition',
  textEmphasisStyle: 'textEmphasisStyle',
  textIndent: 'textIndent',
  textJustify: 'textJustify',
  textOrientation: 'textOrientation',
  textOverflow: 'textOverflow',
  textRendering: 'textRendering',
  textShadow: 'textShadow',
  textTransform: 'textTransform',
  textUnderlinePosition: 'textUnderlinePosition'
};
