version: 2.1

defaults:
  esy_cache: &esy_cache
    key: esy_cache-v2-{{ checksum "compiler/esy.lock.json" }}-{{ .Branch }}
  esy_cache_keys: &esy_cache_keys
    keys:
      - esy_cache-v2-{{ checksum "compiler/esy.lock.json" }}-{{ .Branch }}
      - esy_cache-v2-{{ checksum "compiler/esy.lock.json" }}
      - esy_cache-v2

orbs:
  node: circleci/node@0.0.6

jobs:
  test_compiler:
    executor: node/node
    steps:
      - checkout
      - restore_cache:
          <<: *esy_cache_keys
      - run:
          name: Install
          working_directory: ~/project/compiler
          command: npx esy install
      - run:
          name: Build
          working_directory: ~/project/compiler
          command: npx esy build
      - run:
          name: Test
          working_directory: ~/project/compiler
          command: npx esy test
      - save_cache:
          <<: *esy_cache
          paths:
            - ~/.esy/3_____________________________________________________________/i

workflows:
  test:
    jobs:
      - test_compiler
