version: 2.1

defaults:
  yarn_cache: &yarn_cache
    key: yarn_cache-v1-{{ checksum "yarn.lock" }}-{{ .Branch }}
  yarn_cache_keys: &yarn_cache_keys
    keys:
      - yarn_cache-v1-{{ checksum "yarn.lock" }}-{{ .Branch }}
      - yarn_cache-v1-{{ checksum "yarn.lock" }}
      - yarn_cache-v1

orbs:
  node: circleci/node@0.0.6

jobs:
  test_compiler:
    executor: node/node
    steps:
      - checkout
      - restore_cache:
          <<: *yarn_cache_keys
      - run:
          name: Setup Environment
          command: yarn global add esy
      - run:
          name: Install
          command: |
            cd compiler
            esy install
      - run:
          name: Build
          command: |
            cd compiler
            esy build
      - run:
          name: Test
          command: |
            cd compiler
            esy test
      - save_cache:
          <<: *yarn_cache
          paths:
            - ~/.cache/yarn

workflows:
  test:
    jobs:
      - test_compiler
