version: 2.1

defaults:
  linux_node_cache: &linux_node_cache
    key: linux_node_cache-v1-{{ checksum "yarn.lock" }}-{{ .Branch }}
  linux_node_cache_keys: &linux_node_cache_keys
    keys:
      - linux_node_cache-v1-{{ checksum "yarn.lock" }}-{{ .Branch }}
      - linux_node_cache-v1-{{ checksum "yarn.lock" }}
      - linux_node_cache-v1
  macos_node_cache: &macos_node_cache
    key: macos_node_cache-v1-{{ checksum "yarn.lock" }}-{{ .Branch }}
  macos_node_cache_keys: &macos_node_cache_keys
    keys:
      - macos_node_cache-v1-{{ checksum "yarn.lock" }}-{{ .Branch }}
      - macos_node_cache-v1-{{ checksum "yarn.lock" }}
      - macos_node_cache-v1
  linux_compiler_cache: &linux_compiler_cache
    key: linux_compiler_cache-v1-{{ checksum "compiler/esy.lock/index.json" }}-{{ .Branch }}
  linux_compiler_cache_keys: &linux_compiler_cache_keys
    keys:
      - linux_compiler_cache-v1-{{ checksum "compiler/esy.lock/index.json" }}-{{ .Branch }}
      - linux_compiler_cache-v1-{{ checksum "compiler/esy.lock/index.json" }}
      - linux_compiler_cache-v1
  macos_compiler_cache: &macos_compiler_cache
    key: macos_compiler_cache-v1-{{ checksum "compiler/esy.lock/index.json" }}-{{ .Branch }}
  macos_compiler_cache_keys: &macos_compiler_cache_keys
    keys:
      - macos_compiler_cache-v1-{{ checksum "compiler/esy.lock/index.json" }}-{{ .Branch }}
      - macos_compiler_cache-v1-{{ checksum "compiler/esy.lock/index.json" }}
      - macos_compiler_cache-v1

orbs:
  node: circleci/node@0.0.6

commands:
  restore_linux_node_cache:
    description: restore linux node cache
    steps:
      - restore_cache:
          <<: *linux_node_cache_keys
  restore_linux_compiler_cache:
    description: restore linux compiler cache
    steps:
      - restore_cache:
          <<: *linux_compiler_cache_keys
  setup_yarn:
    description: add yarn globals to the PATH
    steps:
      - run:
          name: Setup Yarn
          command: echo 'export PATH="$(yarn global bin):$PATH"' >> $BASH_ENV
  setup_esy:
    description: install esy
    steps:
      - run:
          name: Setup Esy
          command: yarn global add esy
  setup_lerna:
    description: install lerna
    steps:
      - run:
          name: Setup Lerna
          command: yarn global add lerna
  persist:
    description: persist a directory to the workspace
    parameters:
      to:
        type: string
      path:
        type: string
    steps:
      - run:
          name: Populate Workspace
          command: |
            mkdir -p /tmp/workspace
            cp -RL << parameters.path >> /tmp/workspace/<< parameters.to >>
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - << parameters.to >>
  lerna_install:
    description: install dependencies for a particular package
    parameters:
      pkg:
        type: string
    steps:
      - run:
          name: Install
          command: lerna bootstrap --scope=@knot/<< parameters.pkg >>
  lerna_exec:
    description: execute a command on a particular package
    parameters:
      pkg:
        type: string
      command:
        type: string
    steps:
      - run:
          name: Execute Lerna Command
          command: lerna exec --scope=@knot/<< parameters.pkg >> -- << parameters.command >>
  compiler_install:
    description: use esy to install Compiler OCaml dependencies
    steps:
      - run:
          name: Install Compiler Dependencies
          working_directory: ./compiler
          command: esy install && esy pesy
  node_install:
    description: use yarn to install Node project dependencies
    steps:
      - run:
          name: Install Node Dependencies
          command: yarn install
  build_pkg:
    description: build @knot/*, run its tests and store the resulting built version
    parameters:
      pkg:
        type: string
      path:
        type: string
    steps:
      - restore_linux_node_cache
      - setup_yarn
      - setup_lerna
      - lerna_install:
          pkg: << parameters.pkg >>
      - lerna_exec:
          pkg: << parameters.pkg >>
          command: yarn build
      - lerna_exec:
          pkg: << parameters.pkg >>
          command: yarn test
      - persist:
          path: << parameters.path >>/build
          to: << parameters.pkg >>
  store_cypress_artifacts:
    description: store artifacts from cypress tests
    steps:
      - store_artifacts:
          path: ./examples/webpack-react/cypress/screenshots
      - store_artifacts:
          path: ./examples/webpack-react/cypress/videos

jobs:
  install_node:
    executor: node/node
    steps:
      - checkout
      - restore_linux_node_cache
      - setup_yarn
      - setup_lerna
      - run:
          name: Install
          command: lerna bootstrap
      - save_cache:
          <<: *linux_node_cache
          paths:
            - ~/.cache

  test_compiler:
    executor: node/node
    steps:
      - checkout
      - restore_linux_compiler_cache
      - restore_linux_node_cache
      - setup_yarn
      - setup_esy
      - compiler_install
      - run:
          name: Build
          working_directory: ./compiler
          command: |
            if [ -e ./_export ]; then
              esy import-build ./_export/*.tar.gz
            fi

            esy build
      - run:
          name: Test
          working_directory: ./compiler
          command: yarn test
      - run:
          name: Export Dependencies
          working_directory: ./compiler
          command: esy export-dependencies
      - save_cache:
          <<: *linux_compiler_cache
          paths:
            - ~/project/compiler/_export
      - persist:
          path: compiler/_esy/default/store/i/knot-*
          to: knot

  test_compiler_binary:
    executor: node/node
    steps:
      - checkout
      - build_pkg:
          pkg: compiler
          path: packages/binaries/compiler

  test_browser_plugin:
    executor: node/node
    steps:
      - checkout
      - build_pkg:
          pkg: browser-plugin
          path: packages/plugins/compiler/browser

  test_react_plugin:
    executor: node/node
    steps:
      - checkout
      - build_pkg:
          pkg: react-plugin
          path: packages/plugins/compiler/react

  test_jss_plugin:
    executor: node/node
    steps:
      - checkout
      - build_pkg:
          pkg: jss-plugin
          path: packages/plugins/compiler/jss

  test_webpack_plugin:
    executor: node/node
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Restore Plugins
          working_directory: ./packages
          command: |
            mv /tmp/workspace/compiler binaries/compiler/build
      - build_pkg:
          pkg: webpack-plugin
          path: packages/plugins/bundler/webpack

  test_browserify_plugin:
    executor: node/node
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Restore Plugins
          working_directory: ./packages
          command: |
            mv /tmp/workspace/compiler binaries/compiler/build
      - build_pkg:
          pkg: browserify-plugin
          path: packages/plugins/bundler/browserify

  test_webpack_react:
    docker:
      - image: cypress/base:8
        environment:
          ## this enables colors in the output
          TERM: xterm
          KNOT_BINARY: /tmp/workspace/knot/bin/knotc.exe
    working_directory: ~/app
    steps:
      - checkout
      - restore_linux_node_cache
      - setup_yarn
      - setup_lerna
      - lerna_install:
          pkg: webpack-react-example
      - attach_workspace:
          at: /tmp/workspace
      - setup_esy
      - run:
          name: Restore Plugins
          working_directory: ./packages
          command: |
            mv /tmp/workspace/compiler binaries/compiler/build
            mv /tmp/workspace/browser-plugin plugins/compiler/browser/build
            mv /tmp/workspace/react-plugin plugins/compiler/react/build
            mv /tmp/workspace/jss-plugin plugins/compiler/jss/build
            mv /tmp/workspace/webpack-plugin plugins/bundler/webpack/build
      - lerna_exec:
          pkg: webpack-react-example
          command: yarn test
      - store_cypress_artifacts

  test_browserify_react:
    docker:
      - image: cypress/base:8
        environment:
          ## this enables colors in the output
          TERM: xterm
          KNOT_BINARY: /tmp/workspace/knot/bin/knotc.exe
    working_directory: ~/app
    steps:
      - checkout
      - restore_linux_node_cache
      - setup_yarn
      - setup_lerna
      - lerna_install:
          pkg: browserify-react-example
      - attach_workspace:
          at: /tmp/workspace
      - setup_esy
      - run:
          name: Restore Plugins
          working_directory: ./packages
          command: |
            mv /tmp/workspace/compiler binaries/compiler/build
            mv /tmp/workspace/browser-plugin plugins/compiler/browser/build
            mv /tmp/workspace/react-plugin plugins/compiler/react/build
            mv /tmp/workspace/jss-plugin plugins/compiler/jss/build
            mv /tmp/workspace/browserify-plugin plugins/bundler/browserify/build
      - lerna_exec:
          pkg: browserify-react-example
          command: |
            yarn build
            yarn test
      - store_cypress_artifacts

  compile_macos:
    macos:
      xcode: "11.0.0"
    steps:
      - checkout
      - restore_cache:
          <<: *macos_compiler_cache_keys
      - restore_cache:
          <<: *macos_node_cache_keys
      - setup_esy
      - node_install
      - compiler_install
      - run:
          name: Build Compiler
          command: yarn x build.compiler
      - persist:
          path: ./compiler/_release
          to: compiler_macos
      - save_cache:
          <<: *macos_compiler_cache
          paths:
            - ~/project/compiler/_export
      - save_cache:
          <<: *macos_node_cache
          paths:
            - ~/.cache

  compile_linux:
    executor: node/node
    steps:
      - checkout
      - restore_linux_compiler_cache
      - restore_linux_node_cache
      - setup_yarn
      - setup_esy
      - node_install
      - compiler_install
      - run:
          name: Build Compiler
          command: yarn x build.compiler
      - persist:
          path: ./compiler/_release
          to: compiler_linux

  release:
    executor: node/node
    steps:
      - checkout
      - restore_linux_node_cache
      - setup_yarn
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Retrieve Compiler Artifacts
          working_directory: ./packages/binaries/compiler
          command: |
            mv /tmp/workspace/compiler_macos/* platforms/macos
            mv /tmp/workspace/compiler_linux/* platforms/linux
      - node_install
      - run:
          name: Build Packages
          command: yarn x build.packages
      - run:
          name: Release
          command: yarn release

workflows:
  test_release:
    jobs:
      - install_node
      - test_compiler
      - test_compiler_binary:
          requires:
            - install_node
      - test_browser_plugin:
          requires:
            - install_node
      - test_react_plugin:
          requires:
            - install_node
      - test_jss_plugin:
          requires:
            - install_node
      - test_webpack_plugin:
          requires:
            - test_compiler
      - test_browserify_plugin:
          requires:
            - test_compiler
      - test_webpack_react:
          requires:
            - test_compiler
            - test_compiler_binary
            - test_browser_plugin
            - test_react_plugin
            - test_jss_plugin
            - test_webpack_plugin
      - test_browserify_react:
          requires:
            - test_compiler
            - test_compiler_binary
            - test_browser_plugin
            - test_react_plugin
            - test_jss_plugin
            - test_browserify_plugin
      - compile_macos:
          requires:
            - test_webpack_react
            - test_browserify_react
          filters:
            branches:
              only: master
      - compile_linux:
          requires:
            - test_webpack_react
            - test_browserify_react
          filters:
            branches:
              only: master
      - release:
          requires:
            - compile_macos
            - compile_linux
          filters:
            branches:
              only: master
