version: 2.1

defaults:
  esy_cache: &esy_cache
    key: esy_cache-v3-{{ checksum "compiler/esy.lock.json" }}-{{ .Branch }}
  esy_cache_keys: &esy_cache_keys
    keys:
      - esy_cache-v3-{{ checksum "compiler/esy.lock.json" }}-{{ .Branch }}
      - esy_cache-v3-{{ checksum "compiler/esy.lock.json" }}
      - esy_cache-v3

orbs:
  node: circleci/node@0.0.6

commands:
  setup_esy:
    steps:
      - run:
          name: Setup Esy
          command: |
            echo 'export PATH="$(yarn global bin):$PATH"' >> $BASH_ENV
            yarn global add esy

jobs:
  test_compiler:
    executor: node/node
    steps:
      - checkout
      - restore_cache:
          <<: *esy_cache_keys
      - setup_esy
      - run:
          name: Install
          working_directory: ~/project/compiler
          command: esy install
      - run:
          name: Build
          working_directory: ~/project/compiler
          command: |
            if [ -e ./_export ]; then
              esy import-build ./_export/*.tar.gz
            fi

            esy build
      - run:
          name: Test
          working_directory: ~/project/compiler
          command: yarn test
      - run:
          name: Export Dependencies
          working_directory: ~/project/compiler
          command: esy export-dependencies
      - save_cache:
          <<: *esy_cache
          paths:
            - ~/project/compiler/_export
      - run:
          name: Populate Workspace
          working_directory: ~/project/compiler
          command: |
            mkdir -p /tmp/workspace
            mv _build/default/executable/Compiler.exe /tmp/workspace/Compiler.exe
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - Compiler.exe

  test_webpack_react:
    executor: node/node
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - setup_esy
      # - restore_cache:
      #     <<: *esy_cache_keys
      - run:
          name: Install
          working_directory: ~/project/examples/webpack-react
          command: yarn install
      - run:
          name: Test
          working_directory: ~/project/examples/webpack-react
          environment:
            KNOT_BINARY: /tmp/workspace/Compiler.exe
          command: yarn test
      # - save_cache:
      #     <<: *esy_cache
      #     paths:
      #       - ~/.esy/3_____________________________________________________________/i

workflows:
  test:
    jobs:
      - test_compiler
      - test_webpack_react:
          requires:
            - test_compiler
