version: 2.1

defaults:
  compiler_cache: &compiler_cache
    key: compiler_cache-v4-{{ checksum "compiler/esy.lock.json" }}-{{ .Branch }}
  compiler_cache_keys: &compiler_cache_keys
    keys:
      - compiler_cache-v4-{{ checksum "compiler/esy.lock.json" }}-{{ .Branch }}
      - compiler_cache-v4-{{ checksum "compiler/esy.lock.json" }}
      - compiler_cache-v4
  webpack_loader_cache: &webpack_loader_cache
    key: webpack_loader_cache-v1-{{ checksum "webpack-loader/yarn.lock" }}-{{ .Branch }}
  webpack_loader_cache_keys: &webpack_loader_cache_keys
    keys:
      - webpack_loader_cache-v1-{{ checksum "webpack-loader/yarn.lock" }}-{{ .Branch }}
      - webpack_loader_cache-v1-{{ checksum "webpack-loader/yarn.lock" }}
      - webpack_loader_cache-v1

orbs:
  node: circleci/node@0.0.6

commands:
  setup_esy:
    steps:
      - run:
          name: Setup Esy
          command: |
            echo 'export PATH="$(yarn global bin):$PATH"' >> $BASH_ENV
            yarn global add esy

jobs:
  test_compiler:
    executor: node/node
    steps:
      - checkout
      - restore_cache:
          <<: *compiler_cache_keys
      - setup_esy
      - run:
          name: Install
          working_directory: ~/project/compiler
          command: esy install
      - run:
          name: Build
          working_directory: ~/project/compiler
          command: |
            if [ -e ./_export ]; then
              esy import-build ./_export/*.tar.gz
            fi

            esy build
      - run:
          name: Test
          working_directory: ~/project/compiler
          command: yarn test
      - run:
          name: Export Dependencies
          working_directory: ~/project/compiler
          command: esy export-dependencies
      - save_cache:
          <<: *compiler_cache
          paths:
            - ~/project/compiler/_export
      - run:
          name: Populate Workspace
          working_directory: ~/project/compiler
          command: |
            mkdir -p /tmp/workspace
            cp -L _esy/default/store/i/knot-*/bin/knotc.exe /tmp/workspace/knotc.exe
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - knotc.exe

  test_webpack_react:
    docker:
      - image: cypress/base:8
        environment:
          ## this enables colors in the output
          TERM: xterm
          KNOT_BINARY: /tmp/workspace/knotc.exe
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          <<: *webpack_loader_cache_keys
      - attach_workspace:
          at: /tmp/workspace
      - setup_esy
      - run:
          name: Install
          working_directory: ./examples/webpack-react
          command: yarn install --frozen-lockfile
      - run:
          name: Test
          working_directory: ./examples/webpack-react
          command: yarn test
      - save_cache:
          <<: *webpack_loader_cache
          paths:
            - ~/.cache

workflows:
  test:
    jobs:
      - test_compiler
      - test_webpack_react:
          requires:
            - test_compiler
