version: 2.1

defaults:
  node_cache: &node_cache
    key: node_cache-v1-{{ checksum "yarn.lock" }}-{{ .Branch }}
  node_cache_keys: &node_cache_keys
    keys:
      - node_cache-v1-{{ checksum "yarn.lock" }}-{{ .Branch }}
      - node_cache-v1-{{ checksum "yarn.lock" }}
      - node_cache-v1
  compiler_linux_cache: &compiler_linux_cache
    key: compiler_linux_cache-v1-{{ checksum "compiler/esy.lock/index.json" }}-{{ .Branch }}
  compiler_linux_cache_keys: &compiler_linux_cache_keys
    keys:
      - compiler_linux_cache-v1-{{ checksum "compiler/esy.lock/index.json" }}-{{ .Branch }}
      - compiler_linux_cache-v1-{{ checksum "compiler/esy.lock/index.json" }}
      - compiler_linux_cache-v1
  compiler_macos_cache: &compiler_macos_cache
    key: compiler_macos_cache-v1-{{ checksum "compiler/esy.lock/index.json" }}-{{ .Branch }}
  compiler_macos_cache_keys: &compiler_macos_cache_keys
    keys:
      - compiler_macos_cache-v1-{{ checksum "compiler/esy.lock/index.json" }}-{{ .Branch }}
      - compiler_macos_cache-v1-{{ checksum "compiler/esy.lock/index.json" }}
      - compiler_macos_cache-v1

orbs:
  node: circleci/node@0.0.6

commands:
  setup_yarn:
    description: restore node cache and add yarn globals to the PATH
    steps:
      - restore_cache:
          <<: *node_cache_keys
      - run:
          name: Setup Yarn
          command: echo 'export PATH="$(yarn global bin):$PATH"' >> $BASH_ENV
  setup_esy:
    description: install esy
    steps:
      - run:
          name: Setup Esy
          command: yarn global add esy
  setup_lerna:
    description: install lerna
    steps:
      - run:
          name: Setup Lerna
          command: yarn global add lerna
  persist:
    description: persist a directory to the workspace
    parameters:
      to:
        type: string
      path:
        type: string
    steps:
      - run:
          name: Populate Workspace
          command: |
            mkdir -p /tmp/workspace
            cp -RL << parameters.path >> /tmp/workspace/<< parameters.to >>
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - << parameters.to >>
  lerna_install:
    description: install dependencies for a particular package
    parameters:
      pkg:
        type: string
    steps:
      - run:
          name: Install
          command: lerna bootstrap --scope=@knot/<< parameters.pkg >>
  lerna_exec:
    description: execute a command on a particular package
    parameters:
      pkg:
        type: string
      command:
        type: string
    steps:
      - run:
          name: Execute Lerna Command
          command: lerna exec --scope=@knot/<< parameters.pkg >> -- << parameters.command >>
  compiler_install:
    description: use esy to install Compiler OCaml dependencies
    steps:
      - run:
          name: Install Compiler Dependencies
          working_directory: ./compiler
          command: esy install && esy pesy
  node_install:
    description: use yarn to install Node project dependencies
    steps:
      - run:
          name: Node Install Node Dependencies
          command: yarn install
  build_plugin:
    description: build @knot/*-plugin, run its tests and store the resulting built version
    parameters:
      pkg:
        type: string
      path:
        type: string
    steps:
      - setup_yarn
      - setup_lerna
      - lerna_install:
          pkg: << parameters.pkg >>-plugin
      - lerna_exec:
          pkg: << parameters.pkg >>-plugin
          command: yarn build
      - lerna_exec:
          pkg: << parameters.pkg >>-plugin
          command: yarn test
      - persist:
          path: << parameters.path >>/build
          to: << parameters.pkg >>-plugin
  store_cypress_artifacts:
    description: store artifacts from cypress tests
    steps:
      - store_artifacts:
          path: ./examples/webpack-react/cypress/screenshots
      - store_artifacts:
          path: ./examples/webpack-react/cypress/videos

jobs:
  install_node:
    executor: node/node
    steps:
      - checkout
      - setup_yarn
      - setup_lerna
      - run:
          name: Install
          command: lerna bootstrap
      - save_cache:
          <<: *node_cache
          paths:
            - ~/.cache

  test_compiler:
    executor: node/node
    steps:
      - checkout
      - restore_cache:
          <<: *compiler_linux_cache_keys
      - setup_yarn
      - setup_esy
      - compiler_install
      - run:
          name: Build
          working_directory: ./compiler
          command: |
            if [ -e ./_export ]; then
              esy import-build ./_export/*.tar.gz
            fi

            esy build
      - run:
          name: Test
          working_directory: ./compiler
          command: yarn test
      - run:
          name: Export Dependencies
          working_directory: ./compiler
          command: esy export-dependencies
      - save_cache:
          <<: *compiler_linux_cache
          paths:
            - ~/project/compiler/_export
      - persist:
          path: compiler/_esy/default/store/i/knot-*
          to: knot

  test_react_plugin:
    executor: node/node
    steps:
      - checkout
      - build_plugin:
          pkg: react
          path: packages/plugins/compiler/react

  test_jss_plugin:
    executor: node/node
    steps:
      - checkout
      - build_plugin:
          pkg: jss
          path: packages/plugins/compiler/jss

  test_webpack_plugin:
    executor: node/node
    steps:
      - checkout
      - build_plugin:
          pkg: webpack
          path: packages/plugins/bundler/webpack

  test_webpack_react:
    docker:
      - image: cypress/base:8
        environment:
          ## this enables colors in the output
          TERM: xterm
          KNOT_BINARY: /tmp/workspace/knot/bin/knotc.exe
    working_directory: ~/app
    steps:
      - checkout
      - setup_yarn
      - setup_lerna
      - lerna_install:
          pkg: webpack-react-example
      - attach_workspace:
          at: /tmp/workspace
      - setup_esy
      - run:
          name: Restore Plugins
          working_directory: ./packages/plugins
          command: |
            mv /tmp/workspace/react-plugin compiler/react/build
            mv /tmp/workspace/jss-plugin compiler/jss/build
            mv /tmp/workspace/webpack-plugin bundler/webpack/build
      - lerna_exec:
          pkg: webpack-react-example
          command: yarn test
      - store_cypress_artifacts

  compile_macos:
    macos:
      xcode: "11.0.0"
    steps:
      - checkout
      - restore_cache:
          <<: *compiler_macos_cache_keys
      - setup_yarn
      - setup_esy
      - node_install
      - compiler_install
      - run:
          name: Build Compiler
          command: yarn x build.compiler
      - persist:
          path: ./compiler/_release
          to: compiler_macos
      - save_cache:
          <<: *compiler_macos_cache
          paths:
            - ~/project/compiler/_export

  compile_linux:
    executor: node/node
    steps:
      - checkout
      - restore_cache:
          <<: *compiler_linux_cache_keys
      - setup_yarn
      - setup_esy
      - node_install
      - compiler_install
      - run:
          name: Build Compiler
          command: yarn x build.compiler
      - persist:
          path: ./compiler/_release
          to: compiler_linux

  release:
    executor: node/node
    steps:
      - checkout
      - restore_cache:
          <<: *compiler_linux_cache_keys
      - setup_yarn
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Retrieve Compiler Artifacts
          working_directory: ./packages/binaries/compiler
          command: |
            mv /tmp/workspace/compiler_macos platforms/macos
            mv /tmp/workspace/compiler_linux platforms/linux
      - node_install
      - run:
          name: Build Packages
          command: yarn x build.packages
      - run:
          name: Release
          command: yarn release

  validate_webpack_react:
    docker:
      - image: cypress/base:8
        environment:
          ## this enables colors in the output
          TERM: xterm
          KNOT_BINARY: /tmp/workspace/knot/bin/knotc.exe
    working_directory: ~/app
    steps:
      - checkout
      - setup_yarn
      - setup_lerna
      - run:
          name: Install
          working_directory: ./examples/webpack-react
          ## avoids using the existing yarn workspaces when installing
          ## should be a better indication of the external usability
          command: npm install
      - attach_workspace:
          at: /tmp/workspace
      - setup_esy
      - lerna_exec:
          pkg: webpack-react-example
          command: yarn test
      - store_cypress_artifacts

workflows:
  test_release:
    jobs:
      - install_node
      - test_compiler
      - test_react_plugin:
          requires:
            - install_node
      - test_jss_plugin:
          requires:
            - install_node
      - test_webpack_plugin:
          requires:
            - install_node
      - test_webpack_react:
          requires:
            - test_compiler
            - test_react_plugin
            - test_jss_plugin
            - test_webpack_plugin
      - compile_macos:
          requires:
            - test_webpack_react
          filters:
            branches:
              only: master
      - compile_linux:
          requires:
            - test_webpack_react
          filters:
            branches:
              only: master
      - release:
          requires:
            - compile_macos
            - compile_linux
          filters:
            branches:
              only: master
