version: 2.1

defaults:
  node_cache: &node_cache
    key: node_cache-v1-{{ checksum "yarn.lock" }}-{{ .Branch }}
  node_cache_keys: &node_cache_keys
    keys:
      - node_cache-v1-{{ checksum "yarn.lock" }}-{{ .Branch }}
      - node_cache-v1-{{ checksum "yarn.lock" }}
      - node_cache-v1
  compiler_cache: &compiler_cache
    key: compiler_cache-v4-{{ checksum "compiler/esy.lock.json" }}-{{ .Branch }}
  compiler_cache_keys: &compiler_cache_keys
    keys:
      - compiler_cache-v4-{{ checksum "compiler/esy.lock.json" }}-{{ .Branch }}
      - compiler_cache-v4-{{ checksum "compiler/esy.lock.json" }}
      - compiler_cache-v4

orbs:
  node: circleci/node@0.0.6

commands:
  setup_yarn:
    description: restore node cache and add yarn globals to the PATH
    steps:
      - restore_cache:
          <<: *node_cache_keys
      - run:
          name: Setup Yarn
          command: echo 'export PATH="$(yarn global bin):$PATH"' >> $BASH_ENV
  setup_esy:
    description: install esy
    steps:
      - run:
          name: Setup Esy
          command: yarn global add esy
  setup_lerna:
    description: install lerna
    steps:
      - run:
          name: Setup Lerna
          command: yarn global add lerna
  persist:
    description: persist a directory to the workspace
    parameters:
      to:
        type: string
      path:
        type: string
    steps:
      - run:
          name: Populate Workspace
          command: |
            mkdir -p /tmp/workspace
            cp -RL << parameters.path >> /tmp/workspace/<< parameters.to >>
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - << parameters.to >>
  lerna_install:
    description: install dependencies for a particular package
    parameters:
      name:
        type: string
    steps:
      - run:
          name: Install
          command: lerna bootstrap --scope=@knot/<< parameters.name >>
  lerna_exec:
    description: execute a command on a particular package
    parameters:
      name:
        type: string
      command:
        type: string
    steps:
      - run:
          name: Execute Lerna Command
          command: lerna exec --scope=@knot/<< parameters.name >> -- << parameters.command >>
  build_plugin:
    description: build @knot/*-plugin, run its tests and store the resulting built version
    parameters:
      name:
        type: string
      path:
        type: string
    steps:
      - setup_yarn
      - setup_lerna
      - lerna_install:
          name: << parameters.name >>-plugin
      - lerna_exec:
          name: << parameters.name >>-plugin
          command: yarn build
      - lerna_exec:
          name: << parameters.name >>-plugin
          command: yarn test
      - persist:
          path: << parameters.path >>/build
          to: << parameters.name >>-plugin

jobs:
  install_node:
    executor: node/node
    steps:
      - checkout
      - setup_yarn
      - setup_lerna
      - run:
          name: Install
          command: lerna bootstrap
      - save_cache:
          <<: *node_cache
          paths:
            - ~/.cache

  test_compiler:
    executor: node/node
    steps:
      - checkout
      - restore_cache:
          <<: *compiler_cache_keys
      - setup_yarn
      - setup_esy
      - run:
          name: Install
          working_directory: ./compiler
          command: esy install
      - run:
          name: Build
          working_directory: ./compiler
          command: |
            if [ -e ./_export ]; then
              esy import-build ./_export/*.tar.gz
            fi

            esy build
      - run:
          name: Test
          working_directory: ./compiler
          command: yarn test
      - run:
          name: Export Dependencies
          working_directory: ./compiler
          command: esy export-dependencies
      - save_cache:
          <<: *compiler_cache
          paths:
            - ~/project/compiler/_export
      - persist:
          path: _esy/default/store/i/knot-*
          to: knot

  test_react_plugin:
    executor: node/node
    steps:
      - checkout
      - build_plugin:
          name: react
          path: packages/plugins/compiler/react

  test_jss_plugin:
    executor: node/node
    steps:
      - checkout
      - build_plugin:
          name: jss
          path: packages/plugins/compiler/jss

  test_webpack_plugin:
    executor: node/node
    steps:
      - checkout
      - build_plugin:
          name: webpack
          path: packages/plugins/bundler/webpack

  test_webpack_react:
    docker:
      - image: cypress/base:8
        environment:
          ## this enables colors in the output
          TERM: xterm
          KNOT_BINARY: /tmp/workspace/knot/bin/knotc.exe
    working_directory: ~/app
    steps:
      - checkout
      - setup_yarn
      - setup_lerna
      - lerna_install:
          name: webpack-react-example
      - attach_workspace:
          at: /tmp/workspace
      - setup_esy
      - run:
          name: Restore Plugins
          working_directory: ./packages/plugins
          command: |
            mv /tmp/workspace/react-plugin compiler/react/build
            mv /tmp/workspace/jss-plugin compiler/jss/build
            mv /tmp/workspace/webpack-plugin bundler/webpack/build
      - lerna_exec:
          name: webpack-react-example
          command: yarn test
      - store_artifacts:
          path: ./examples/webpack-react/cypress/screenshots
      - store_artifacts:
          path: ./examples/webpack-react/cypress/videos

  release:
    executor: node/node
    steps:
      - checkout
      - run:
          name: Release
          command: yarn release

workflows:
  test_release:
    jobs:
      - install_node
      - test_compiler
      - test_react_plugin:
          requires:
            - install_node
      - test_jss_plugin:
          requires:
            - install_node
      - test_webpack_plugin:
          requires:
            - install_node
      - test_webpack_react:
          requires:
            - test_compiler
            - test_react_plugin
            - test_jss_plugin
            - test_webpack_plugin
      - release:
          requires:
            - test_webpack_react
