flowchart LR
  X{{"#quot;@/myModule#quot;"}}

  X --> |input| Resolver

  Grammar -.-> Parser

  %% compile
  subgraph Compiler
    Resolver --> Module --> InputStream --> Parser
  end
  Parser --> Generator --> Writer --> Y([**compiled code**])

  Analyzer --> Parser

