<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <!-- Generated via Iro -->
  <dict>
    <key>fileTypes</key>
    <array>
      <string>kn</string>
    </array>
    <key>name</key>
    <string>knot</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#main</string>
      </dict>
    </array>
    <key>scopeName</key>
    <string>source.knot</string>
    <key>uuid</key>
    <string></string>
    <key>repository</key>
    <dict>
      <key>main</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#keyword</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#declaration</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#storage</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#type_definition</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#parameterized_type</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#jsx</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#block_closure</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#primitive</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#group_closure</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#operator</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#punctuation</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#identifier</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#whitespace</string>
          </dict>
        </array>
      </dict>
      <key>block_closure</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(\s*)({)(\s*)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#block_closure__1</string>
              </dict>
            </array>
            <key>end</key>
            <string>(\s*)(})(\s*)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>block_closure__1</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#main</string>
          </dict>
        </array>
      </dict>
      <key>boolean</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(\btrue\b)</string>
            <key>name</key>
            <string>constant.language.boolean.true.knot</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(\bfalse\b)</string>
            <key>name</key>
            <string>constant.language.boolean.false.knot</string>
          </dict>
        </array>
      </dict>
      <key>declaration</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(\bconst\b)(\s+)(\b[_a-zA-Z]\w+\b)(\s*)(=)(\s*)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>variable.other.constant.knot</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.assignment.knot</string>
              </dict>
              <key>6</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(\blet\b)(\s+)(\b[_a-zA-Z]\w+\b)(\s*)(=)(\s*)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>variable.other.knot</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.assignment.knot</string>
              </dict>
              <key>6</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(\bconst\b)(\s+)(\b[_a-zA-Z]\w+\b)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>variable.other.constant.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(\blet\b)(\s+)(\b[_a-zA-Z]\w+\b)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>variable.other.knot</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>group_closure</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(\s*)(\()(\s*)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>meta.brace.round.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#group_closure__1</string>
              </dict>
            </array>
            <key>end</key>
            <string>(\s*)(\))(\s*)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>meta.brace.round.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>group_closure__1</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#main</string>
          </dict>
        </array>
      </dict>
      <key>identifier</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(\b[_a-zA-Z]\w+\b)</string>
            <key>name</key>
            <string>variable.knot</string>
          </dict>
        </array>
      </dict>
      <key>jsx</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#jsx_ambiguity_guards</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(&lt;)(\s*)(\b_?[a-z]\w*\b)(\s*)(/\s*&gt;)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.knot</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.end.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(&lt;)(\s*)(\b_?[A-Z]\w*\b)(\s*)(/\s*&gt;)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>support.class.view.knot</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.end.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>begin</key>
            <string>(&lt;)(\s*)(\b_?[a-z]\w*\b)(\s*)(&gt;)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.knot</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.end.knot</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#jsx__1</string>
              </dict>
            </array>
            <key>end</key>
            <string>(&lt;\s*/)(\s*)(\b_?[a-z]\w*\b)(\s*)(&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.knot</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.end.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>begin</key>
            <string>(&lt;)(\s*)(\b_?[A-Z]\w*\b)(\s*)(&gt;)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>support.class.view.knot</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.end.knot</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#jsx__2</string>
              </dict>
            </array>
            <key>end</key>
            <string>(&lt;\s*/)(\s*)(\b_?[A-Z]\w*\b)(\s*)(&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>support.class.view.knot</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.end.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>begin</key>
            <string>(&lt;)(\s*)(\b_?[a-z]\w*\b)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.knot</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#jsx__3</string>
              </dict>
            </array>
            <key>end</key>
            <string>(?:(\b_?[a-z]\w*\b\s*)(&gt;))|(/\s*&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.end.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.end.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>begin</key>
            <string>(&lt;)(\s*)(\b_?[A-Z]\w*\b)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>support.class.view.knot</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#jsx__5</string>
              </dict>
            </array>
            <key>end</key>
            <string>(?:(\b_?[A-Z]\w*\b\s*)(&gt;))|(/\s*&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.class.view.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.end.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.end.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>include</key>
            <string>#jsx_fragment</string>
          </dict>
        </array>
      </dict>
      <key>jsx__1</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#jsx_inner</string>
          </dict>
        </array>
      </dict>
      <key>jsx__2</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#jsx_inner</string>
          </dict>
        </array>
      </dict>
      <key>jsx__3</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(&gt;)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.end.knot</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#jsx__4</string>
              </dict>
            </array>
            <key>end</key>
            <string>(&lt;\s*/)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>include</key>
            <string>#jsx_tag_attribute</string>
          </dict>
        </array>
      </dict>
      <key>jsx__4</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#jsx_inner</string>
          </dict>
        </array>
      </dict>
      <key>jsx__5</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(&gt;)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.end.knot</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#jsx__6</string>
              </dict>
            </array>
            <key>end</key>
            <string>(&lt;\s*/)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>include</key>
            <string>#jsx_tag_attribute</string>
          </dict>
        </array>
      </dict>
      <key>jsx__6</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#jsx_inner</string>
          </dict>
        </array>
      </dict>
      <key>jsx_ambiguity_guards</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(\b[_a-zA-Z]\w+\b)(\s*)(&lt;)(\s*)((?:\b_?[a-z]\w*\b|\b_?[A-Z]\w*\b)(?!\s*(?:/\s*&gt;|[\x{003e}_a-zA-Z])))</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.relational.knot</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>variable.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>((?:-\d+\.\d+)|(?:\d+\.\d+))(\s*)(&lt;)(\s*)((?:\b_?[a-z]\w*\b|\b_?[A-Z]\w*\b)(?!\s*(?:/\s*&gt;|[\x{003e}_a-zA-Z])))</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>constant.numeric.decimal.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.relational.knot</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>variable.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>((?:-\d+)|(?:\d+))(\s*)(&lt;)(\s*)((?:\b_?[a-z]\w*\b|\b_?[A-Z]\w*\b)(?!\s*(?:/\s*&gt;|[\x{003e}_a-zA-Z])))</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>constant.numeric.integer.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.relational.knot</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>variable.knot</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>jsx_fragment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(&lt;\s*&gt;)</string>
            <key>name</key>
            <string>punctuation.definition.tag.begin.knot</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(&lt;\s*/\s*&gt;)</string>
            <key>name</key>
            <string>punctuation.definition.tag.end.knot</string>
          </dict>
        </array>
      </dict>
      <key>jsx_inner</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#block_closure</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#jsx</string>
          </dict>
          <dict>
            <key>match</key>
            <string>([^\x{003c}\x{007b}]+)</string>
            <key>name</key>
            <string>string.unquoted.knot</string>
          </dict>
        </array>
      </dict>
      <key>jsx_tag_attribute</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#group_closure</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(\s*)(\b[_a-zA-Z]\w+\b)(\s*)(=)(\s*(?!(?:\btrue\b|\bfalse\b|\bnil\b)))(\b[_a-zA-Z]\w+\b)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.other.attribute-name.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.assignment.knot</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>6</key>
              <dict>
                <key>name</key>
                <string>variable.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(\s*)(\b[_a-zA-Z]\w+\b)(\s*)(=)(\s*)(\btrue\b)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.other.attribute-name.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.assignment.knot</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>6</key>
              <dict>
                <key>name</key>
                <string>constant.language.boolean.true.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(\s*)(\b[_a-zA-Z]\w+\b)(\s*)(=)(\s*)(\bfalse\b)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.other.attribute-name.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.assignment.knot</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>6</key>
              <dict>
                <key>name</key>
                <string>constant.language.boolean.false.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(\s*)(\b[_a-zA-Z]\w+\b)(\s*)(=)(\s*)(\bnil\b)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.other.attribute-name.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.assignment.knot</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>6</key>
              <dict>
                <key>name</key>
                <string>constant.language.boolean.nil.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(=)</string>
            <key>name</key>
            <string>keyword.operator.assignment.knot</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#primitive</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(\b[_a-zA-Z]\w+\b)</string>
            <key>name</key>
            <string>entity.other.attribute-name.knot</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#jsx</string>
          </dict>
        </array>
      </dict>
      <key>keyword</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(\s*)(\bmain\b)(\s*)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.control.main.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(\s*)(\bimport\b)(\s*)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.control.import.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(\s*)(\bfrom\b)(\s*)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.control.from.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(\s*)(\bas\b)(\s*)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.control.as.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(\bimport\b|\bfrom\b|\bas\b|\bmain\b)</string>
            <key>name</key>
            <string>keyword.control.knot</string>
          </dict>
        </array>
      </dict>
      <key>numeric</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>((?:-\d+\.\d+)|(?:\d+\.\d+))</string>
            <key>name</key>
            <string>constant.numeric.decimal.knot</string>
          </dict>
          <dict>
            <key>match</key>
            <string>((?:-\d+)|(?:\d+))</string>
            <key>name</key>
            <string>constant.numeric.integer.knot</string>
          </dict>
        </array>
      </dict>
      <key>operator</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(&lt;=|&gt;=|&lt;|&gt;)</string>
            <key>name</key>
            <string>keyword.operator.relational.knot</string>
          </dict>
          <dict>
            <key>match</key>
            <string>([\x{002b}\-\x{002a}\x{002f}\x{005e}])</string>
            <key>name</key>
            <string>keyword.operator.arithmetic.knot</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(\|\||&amp;&amp;|!)</string>
            <key>name</key>
            <string>keyword.operator.logical.knot</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(==|!=)</string>
            <key>name</key>
            <string>keyword.operator.equality.knot</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(=)</string>
            <key>name</key>
            <string>keyword.operator.assignment.knot</string>
          </dict>
        </array>
      </dict>
      <key>parameterized_type</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>([A-Z]\w*)(&lt;)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.alias.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.typeparameters.begin.knot</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#parameterized_type__1</string>
              </dict>
            </array>
            <key>end</key>
            <string>(&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.typeparameters.end.knot</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>parameterized_type__1</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(\s*)(,)(\s*)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(@)((?:/\w+)+)(#)([^\x{003e}]+)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>string.quoted.double.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>string.quoted.double.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.knot</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>variable.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(\bbool\b|\bnil\b|\bint\b|\bfloat\b|\bstring\b|\belement\b)</string>
            <key>name</key>
            <string>support.type.primitive.knot</string>
          </dict>
          <dict>
            <key>match</key>
            <string>([A-Z]\w*)</string>
            <key>name</key>
            <string>entity.name.type.alias.knot</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#parameterized_type</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#identifier</string>
          </dict>
        </array>
      </dict>
      <key>primitive</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(\bnil\b)</string>
            <key>name</key>
            <string>constant.language.boolean.nil.knot</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#boolean</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#numeric</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string</string>
          </dict>
        </array>
      </dict>
      <key>punctuation</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(;)</string>
            <key>name</key>
            <string>punctuation.terminal.statement.knot</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(,)</string>
            <key>name</key>
            <string>punctuation.separator.comma.knot</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(\(|\))</string>
            <key>name</key>
            <string>meta.brace.round.knot</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(\{|\})</string>
            <key>name</key>
            <string>punctuation.definition.block.knot</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(&lt;/|/&gt;|[\x{003a}])</string>
            <key>name</key>
            <string>punctuation.knot</string>
          </dict>
        </array>
      </dict>
      <key>storage</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(\bconst\b|\blet\b)</string>
            <key>name</key>
            <string>storage.type.knot</string>
          </dict>
        </array>
      </dict>
      <key>string</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(\&quot;)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.knot</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>string.quoted.double.knot</string>
            <key>end</key>
            <string>(\&quot;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.knot</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>string__1</key>
      <dict>
        <key>patterns</key>
        <array>
        </array>
      </dict>
      <key>type_definition</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>((?:\b[_a-zA-Z]\w+\b)?)(\s*)(:)(\s*)(\bbool\b|\bnil\b|\bint\b|\bfloat\b|\bstring\b|\belement\b)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.other.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.type.annotation.knot</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>support.type.primitive.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>((?:\b[_a-zA-Z]\w+\b)?)(\s*)(:)(\s*)([A-Z]\w+)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.other.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.type.annotation.knot</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.alias.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(\btype\b)(\s*)(\bbool\b|\bnil\b|\bint\b|\bfloat\b|\bstring\b|\belement\b)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.type.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>support.type.primitive.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(\btype\b)</string>
            <key>name</key>
            <string>storage.type.type.knot</string>
          </dict>
        </array>
      </dict>
      <key>whitespace</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(\s+)</string>
            <key>name</key>
            <string>text.knot</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>
