<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <!-- Generated via Iro -->
  <dict>
    <key>fileTypes</key>
    <array>
      <string>kn</string>
      <string>knot</string>
    </array>
    <key>name</key>
    <string>knot</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#main</string>
      </dict>
    </array>
    <key>scopeName</key>
    <string>source.knot</string>
    <key>uuid</key>
    <string></string>
    <key>repository</key>
    <dict>
      <key>main</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#main_keyword</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#import</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#entity</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#closure</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#catch_all</string>
          </dict>
        </array>
      </dict>
      <key>boolean</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(\btrue\b)</string>
            <key>name</key>
            <string>constant.language.boolean.true.knot</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(\bfalse\b)</string>
            <key>name</key>
            <string>constant.language.boolean.false.knot</string>
          </dict>
        </array>
      </dict>
      <key>catch_all</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#keyword</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#expression</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#jsx</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#type_definition</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#operator</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#punctuation</string>
          </dict>
          <dict>
            <key>match</key>
            <string>([^\s])</string>
            <key>name</key>
            <string>invalid.knot</string>
          </dict>
        </array>
      </dict>
      <key>closure</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(\{)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.knot</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#uid_braces_closure</string>
              </dict>
            </array>
            <key>end</key>
            <string>(\})</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>begin</key>
            <string>(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>meta.brace.round.knot</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#uid_parentheses_closure</string>
              </dict>
            </array>
            <key>end</key>
            <string>(\))</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>meta.brace.round.knot</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>closure_list</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#closure</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#catch_all</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(,)</string>
            <key>name</key>
            <string>punctuation.separator.comma.knot</string>
          </dict>
        </array>
      </dict>
      <key>comment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(/\*)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>comment.knot</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>comment.knot</string>
            <key>end</key>
            <string>(\*/)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>comment.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(//.*)</string>
            <key>name</key>
            <string>comment.knot</string>
          </dict>
        </array>
      </dict>
      <key>constant_entity</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(\bconst\b)(\s*)([_a-zA-Z]\w*\b)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>variable.other.constant.knot</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>dot_access</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(\.)(\s*)(\b[_a-zA-Z]\w*\b)(\s*)(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.accessor.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.knot</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>punctuation.knot</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#dot_access__1</string>
              </dict>
            </array>
            <key>end</key>
            <string>(\))</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(\.)(\s*)([_a-zA-Z]\w*\b)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.accessor.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>variable.other.object.property.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(\.)</string>
            <key>name</key>
            <string>punctuation.accessor.knot</string>
          </dict>
        </array>
      </dict>
      <key>dot_access__1</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#closure_list</string>
          </dict>
        </array>
      </dict>
      <key>entity</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#constant_entity</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#variable_entity</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#function_entity</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#view_entity</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#state_entity</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#style_entity</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(\bconst\b|\bview\b|\bfunc\b|\bstate\b|\bstyle\b|\blet\b)(\s*)([_a-zA-Z]\w*\b)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.knot</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>entity_parameters</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(,)</string>
            <key>name</key>
            <string>punctuation.separator.comma.knot</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(\b[_a-zA-Z]\w*\b)</string>
            <key>name</key>
            <string>variable.parameter.knot</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#catch_all</string>
          </dict>
        </array>
      </dict>
      <key>expression</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#numeric</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#boolean</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#function_call</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#dot_access</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#identifier</string>
          </dict>
        </array>
      </dict>
      <key>function_call</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(\B\$)([_a-zA-Z]\w*\b)(\s*)(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.accessor.injected.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>punctuation.knot</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#function_call__1</string>
              </dict>
            </array>
            <key>end</key>
            <string>(\))</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>begin</key>
            <string>(\b[_a-zA-Z]\w*\b)(\s*)(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.knot</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#function_call__2</string>
              </dict>
            </array>
            <key>end</key>
            <string>(\))</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.knot</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>function_call__1</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#closure_list</string>
          </dict>
        </array>
      </dict>
      <key>function_call__2</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#closure_list</string>
          </dict>
        </array>
      </dict>
      <key>function_entity</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(\bfunc\b)(\s*)([_a-zA-Z]\w*\b)(\s*)(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.knot</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.parameters.begin.knot</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#function_entity__1</string>
              </dict>
            </array>
            <key>end</key>
            <string>(\))</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.parameters.end.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(\bfunc\b)(\s*)([_a-zA-Z]\w*\b)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.knot</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>function_entity__1</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#entity_parameters</string>
          </dict>
        </array>
      </dict>
      <key>identifier</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(\b[A-Z][_0-9A-Z]*\b)</string>
            <key>name</key>
            <string>variable.other.constant.knot</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(\b[A-Z]\w*\b)</string>
            <key>name</key>
            <string>entity.name.type.module.knot</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(\B\$)([_a-zA-Z]\w*\b)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.accessor.injected.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.other.member.injected.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(\b[_a-zA-Z]\w*\b)</string>
            <key>name</key>
            <string>variable.knot</string>
          </dict>
        </array>
      </dict>
      <key>import</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(\bimport\b)(\s*)(\*)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.import.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>constant.language.import-all.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(\bimport\b)</string>
            <key>name</key>
            <string>keyword.control.import.knot</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(\bfrom\b)</string>
            <key>name</key>
            <string>keyword.control.from.knot</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(\bas\b)(\s*)(\b[_a-zA-Z]\w*\b)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.as.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>variable.other.alias.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(\bas\b)</string>
            <key>name</key>
            <string>keyword.control.as.knot</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(\b[_a-zA-Z]\w*\b)(\s*)(\bfrom\b)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.other.alias.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.control.from.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(\b[_a-zA-Z]\w*\b)(\s*)(\bas\b)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.other.alias.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.control.as.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(\b[_a-zA-Z]\w*\b)(\s*)(\bas\b)(\s*)(\b[_a-zA-Z]\w*\b)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.other.alias.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.control.as.knot</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>variable.other.alias.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(\*)(\s*)(\bas\b)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>constant.language.import-all.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.control.as.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>include</key>
            <string>#import_closure</string>
          </dict>
        </array>
      </dict>
      <key>import_closure</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(\bimport\b)(\s*)(\{)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.import.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.knot</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#uid_parentheses_import_closure</string>
              </dict>
            </array>
            <key>end</key>
            <string>(\})</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.knot</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>import_closure_list</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(,)</string>
            <key>name</key>
            <string>punctuation.separator.comma.knot</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(\b[_a-zA-Z]\w*\b)</string>
            <key>name</key>
            <string>variable.other.alias.knot</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#main</string>
          </dict>
        </array>
      </dict>
      <key>jsx</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(&lt;/)(\s*)([A-Z][a-zA-Z]\w*\b)(\s*)(&gt;)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>support.class.view.knot</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.end.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(&lt;/)(\s*)([a-zA-Z]\w*\b)(\s*)(&gt;)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.knot</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.end.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>begin</key>
            <string>(&lt;)(\s*)([A-Z][a-zA-Z]\w*\b)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>support.class.view.knot</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#uid_self_closing_jsx</string>
              </dict>
            </array>
            <key>end</key>
            <string>(/\s*&gt;|&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.end.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>begin</key>
            <string>(&lt;)(\s*)([a-zA-Z]\w*\b)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.knot</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#uid_self_closing_jsx</string>
              </dict>
            </array>
            <key>end</key>
            <string>(/\s*&gt;|&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.end.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(&lt;)(\s*)(&gt;)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.end.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(&lt;\s*/)(\s*)(&gt;)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.end.knot</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>jsx_tag_attributes</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(\b[_a-zA-Z]\w*\b)(\s*)(=)(\s*)(\&quot;[^\x{0022}]*\&quot;)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.other.attribute-name.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.assignment.knot</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>string.quoted.double.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>begin</key>
            <string>(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>meta.brace.round.knot</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#jsx_tag_attributes__1</string>
              </dict>
            </array>
            <key>end</key>
            <string>(\))</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>meta.brace.round.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>begin</key>
            <string>(\b[_a-zA-Z]\w*\b)(\s*)(=)(\s*)({)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.other.attribute-name.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.assignment.knot</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.embedded.begin.knot</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#jsx_tag_attributes__2</string>
              </dict>
            </array>
            <key>end</key>
            <string>(})</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.embedded.nd.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(\b[_a-zA-Z]\w*\b)</string>
            <key>name</key>
            <string>entity.other.attribute-name.knot</string>
          </dict>
        </array>
      </dict>
      <key>jsx_tag_attributes__1</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(\.[_a-zA-Z]\w*\b)</string>
            <key>name</key>
            <string>entity.other.attribute-name.style-rule.knot</string>
          </dict>
        </array>
      </dict>
      <key>jsx_tag_attributes__2</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#main</string>
          </dict>
        </array>
      </dict>
      <key>keyword</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(\bmut\b)(\s*)(\b[_a-zA-Z]\w*\b)(\s*)(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.property.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.knot</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.parameters.begin.knot</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#keyword__1</string>
              </dict>
            </array>
            <key>end</key>
            <string>(\))</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.parameters.end.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(\bmut\b)(\s*)(\b[_a-zA-Z]\w*\b)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.property.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(\bmut\b|\bget\b)</string>
            <key>name</key>
            <string>storage.type.property.knot</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(\bimport\b|\bfrom\b|\bas\b|\bmain\b)</string>
            <key>name</key>
            <string>keyword.control.knot</string>
          </dict>
        </array>
      </dict>
      <key>keyword__1</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#entity_parameters</string>
          </dict>
        </array>
      </dict>
      <key>main_keyword</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(\bmain\b)</string>
            <key>name</key>
            <string>keyword.control.main.knot</string>
          </dict>
        </array>
      </dict>
      <key>numeric</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(\B-\d+)|(\b\d+)</string>
            <key>name</key>
            <string>constant.numeric.decimal.knot</string>
          </dict>
        </array>
      </dict>
      <key>operator</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(-\s*&gt;)</string>
            <key>name</key>
            <string>storage.type.function.arrow.knot</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(&lt;=|&gt;=|&lt;|&gt;)</string>
            <key>name</key>
            <string>keyword.operator.relational.knot</string>
          </dict>
          <dict>
            <key>match</key>
            <string>([\x{002b}\-\x{002a}\x{002f}])</string>
            <key>name</key>
            <string>keyword.operator.arithmetic.knot</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(\|\||&amp;&amp;|!)</string>
            <key>name</key>
            <string>keyword.operator.logical.knot</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(=)</string>
            <key>name</key>
            <string>keyword.operator.assignment.knot</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(==|!=|[\x{003d}\x{007e}])</string>
            <key>name</key>
            <string>keyword.operator.knot</string>
          </dict>
        </array>
      </dict>
      <key>punctuation</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(;)</string>
            <key>name</key>
            <string>punctuation.terminal.statement.knot</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(,)</string>
            <key>name</key>
            <string>punctuation.separator.comma.knot</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(\(|\))</string>
            <key>name</key>
            <string>meta.brace.round.knot</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(\{|\})</string>
            <key>name</key>
            <string>punctuation.definition.block.knot</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(&lt;/|/&gt;|[\x{003a}\x{003b}\x{003c}\x{003e}])</string>
            <key>name</key>
            <string>punctuation.knot</string>
          </dict>
        </array>
      </dict>
      <key>state_entity</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(\bstate\b)(\s*)([_a-zA-Z]\w*\b)(\s*)(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.state.knot</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.parameters.begin.knot</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#state_entity__1</string>
              </dict>
            </array>
            <key>end</key>
            <string>(\))</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.parameters.end.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>begin</key>
            <string>(\bstate\b)(\s*)([_a-zA-Z]\w*\b)(\s*)(\{)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.state.knot</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.knot</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#state_entity__2</string>
              </dict>
            </array>
            <key>end</key>
            <string>(\})</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(\bstate\b)(\s*)([_a-zA-Z]\w*\b)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.state.knot</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>state_entity__1</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#entity_parameters</string>
          </dict>
        </array>
      </dict>
      <key>state_entity__2</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(\b[_a-zA-Z]\w*\b)(\s*)(=)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.object.property.state.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.assignment.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>include</key>
            <string>#main</string>
          </dict>
        </array>
      </dict>
      <key>string</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(\&quot;)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.knot</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>string.quoted.double.knot</string>
            <key>end</key>
            <string>(\&quot;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.knot</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>string__1</key>
      <dict>
        <key>patterns</key>
        <array>
        </array>
      </dict>
      <key>style_entity</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(\bstyle\b)(\s*)([_a-zA-Z]\w*\b)(\s*)(\{)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.style.knot</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.knot</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#style_entity__1</string>
              </dict>
            </array>
            <key>end</key>
            <string>(\})</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(\bstyle\b)(\s*)([_a-zA-Z]\w*\b)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.style.knot</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>style_entity__1</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#style_rule</string>
          </dict>
        </array>
      </dict>
      <key>style_rule</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(\.[_a-zA-Z]\w*\b)(\s*)(\{)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.other.attribute-name.style-rule.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.knot</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#style_rule__1</string>
              </dict>
            </array>
            <key>end</key>
            <string>(\})</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(\.[_a-zA-Z]\w*\b)</string>
            <key>name</key>
            <string>entity.other.attribute-name.style-rule.knot</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#catch_all</string>
          </dict>
        </array>
      </dict>
      <key>style_rule__1</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(:)</string>
            <key>name</key>
            <string>punctuation.separator.key-value.knot</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#catch_all</string>
          </dict>
        </array>
      </dict>
      <key>type_definition</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(:)(\s*)(\bstring\b|\bnumber\b|\bboolean\b)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.type.annotation.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>support.type.primitive.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(:)(\s*)([_a-zA-Z]\w*\b)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.type.annotation.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.knot</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>uid_block_comment</key>
      <dict>
        <key>patterns</key>
        <array>
        </array>
      </dict>
      <key>uid_braces_closure</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#main</string>
          </dict>
        </array>
      </dict>
      <key>uid_parentheses_closure</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#closure_list</string>
          </dict>
        </array>
      </dict>
      <key>uid_parentheses_import_closure</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#import_closure_list</string>
          </dict>
        </array>
      </dict>
      <key>uid_self_closing_jsx</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#jsx_tag_attributes</string>
          </dict>
        </array>
      </dict>
      <key>variable_entity</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(\blet\b)(\s*)([_a-zA-Z]\w*\b)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>variable.other.knot</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>view_entity</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(\bview\b)(\s*)([_a-zA-Z]\w*\b)(\s*)(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.view.knot</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.parameters.begin.knot</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#view_entity__1</string>
              </dict>
            </array>
            <key>end</key>
            <string>(\))</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.parameters.end.knot</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(\bview\b)(\s*)([_a-zA-Z]\w*\b)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.knot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.knot</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.view.knot</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>view_entity__1</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#entity_parameters</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>
