<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array>
    <string>kn</string>
    <string>knot</string>
   </array>
  <key>name</key>
  <string>knot</string>
  <key>patterns</key>
  <array>
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.knot</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#keyword</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#entity</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#closure</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#catch_all</string>
        </dict>
       </array>
    </dict>
    <key>boolean</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(true|false)</string>
          <key>name</key>
          <string>constant.language.boolean.knot</string>
        </dict>
       </array>
    </dict>
    <key>catch_all</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#expression</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#operator</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#punctuation</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([^\s])</string>
          <key>name</key>
          <string>invalid.knot</string>
        </dict>
       </array>
    </dict>
    <key>closure</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>(\{)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword punctuation.knot</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#uid_braces_closure</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword punctuation.knot</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword punctuation.knot</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#uid_parentheses_closure</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword punctuation.knot</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\[)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword punctuation.knot</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#uid_brackets_closure</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\])</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword punctuation.knot</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>closure_list</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#closure</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#catch_all</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(,)</string>
          <key>name</key>
          <string>keyword punctuation.knot</string>
        </dict>
       </array>
    </dict>
    <key>comment</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>(/*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.knot</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>comment.knot</string>
          <key>end</key>
          <string>(*/)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.knot</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(//.*)</string>
          <key>name</key>
          <string>comment.knot</string>
        </dict>
       </array>
    </dict>
    <key>entity</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#state</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(const|view|func|state|style|let)(\s*)(\w[\w]*)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.knot</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.knot</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>entity.name.knot</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>expression</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#string</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#boolean</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#function_call</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#identifier</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#jsx</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#type_definition</string>
        </dict>
       </array>
    </dict>
    <key>function_call</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>(\w[\w]*)(\s*)(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>meta.function-call.knot</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.knot</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>keyword punctuation.knot</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#function_call__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword punctuation.knot</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>function_call__1</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#closure_list</string>
        </dict>
       </array>
    </dict>
    <key>identifier</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(\B\$\w[\w]*)</string>
          <key>name</key>
          <string>variable.parameter.injected.knot</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b\w[\w]*)</string>
          <key>name</key>
          <string>variable.knot</string>
        </dict>
       </array>
    </dict>
    <key>jsx</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(&lt;/)(\s*)(\w[\w]*)(\s*)(&gt;)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword punctuation.knot</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.knot</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>entity.name.tag.jsx.knot</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>text.knot</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>keyword punctuation.knot</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(&lt;)(\s*)(\w[\w]*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword punctuation.knot</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.knot</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>entity.name.tag.jsx.knot</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#uid_self_closing_jsx</string>
            </dict>
           </array>
          <key>end</key>
          <string>(/&gt;|&gt;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword punctuation.knot</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>jsx__2</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>keyword</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(import|from|main|as)</string>
          <key>name</key>
          <string>keyword.knot</string>
        </dict>
       </array>
    </dict>
    <key>numeric</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(\B-\d+)|(\b\d+)</string>
          <key>name</key>
          <string>constant.numeric.knot</string>
        </dict>
       </array>
    </dict>
    <key>operator</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(-&gt;|==|!=|\|\||&amp;&amp;|[\x{003d}.\x{002b}\-\x{002a}\x{002f}\x{007e}\x{0021}])</string>
          <key>name</key>
          <string>keyword.operator.knot</string>
        </dict>
       </array>
    </dict>
    <key>punctuation</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(&lt;/|/&gt;|[\x{003a}\x{003b}\x{002c}\x{003c}\x{003e}])</string>
          <key>name</key>
          <string>keyword punctuation.knot</string>
        </dict>
       </array>
    </dict>
    <key>state</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>\b(state)(\s*)(\w[\w]*)(\s*)({)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.knot</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.knot</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>entity.name.knot</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>text.knot</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>keyword punctuation.knot</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#state__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword punctuation.knot</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>state__1</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#state_property</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>state_property</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>\b(mut|get)(\s*)(\w[\w]*)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.knot</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.knot</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>meta.function-call.knot</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(-&gt;)(\s*)({)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.operator.knot</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.knot</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>keyword punctuation.knot</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#state_property__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword punctuation.knot</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(-&gt;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.operator.knot</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#state_property__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(;)|(?=mut|get)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword punctuation.knot</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b\w[\w]*)</string>
          <key>name</key>
          <string>entity.other.attribute-name.knot</string>
        </dict>
       </array>
    </dict>
    <key>state_property__1</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>state_property__2</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>string</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>(\&quot;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.quoted.double.knot</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>string.quoted.double.knot</string>
          <key>end</key>
          <string>(\&quot;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.quoted.double.knot</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>string__1</key>
    <dict>
      <key>patterns</key>
      <array>
       </array>
    </dict>
    <key>type_definition</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(:)(\s*)(\w[\w]*)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword punctuation.knot</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.knot</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>entity.name.type.knot</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>uid_block_comment</key>
    <dict>
      <key>patterns</key>
      <array>
       </array>
    </dict>
    <key>uid_braces_closure</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>uid_brackets_closure</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#closure_list</string>
        </dict>
       </array>
    </dict>
    <key>uid_parentheses_closure</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#closure_list</string>
        </dict>
       </array>
    </dict>
    <key>uid_self_closing_jsx</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(\b\w[\w]*)(\s*)(=)(\s*)(\&quot;[^\x{0022}]*\&quot;)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.other.attribute-name.jsx.knot</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.knot</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>keyword punctuation.knot</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>text.knot</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>string.quoted.double.knot</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\b\w[\w]*)(\s*)(=)(\s*)({)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.other.attribute-name.jsx.knot</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.knot</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>keyword punctuation.knot</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>text.knot</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>keyword punctuation.knot</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#jsx__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword punctuation.knot</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b\w[\w]*)</string>
          <key>name</key>
          <string>entity.other.attribute-name.jsx.knot</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
