open Kore;

let tests = [
  Declaration_ConstantTest.suite,
  Declaration_FunctionTest.suite,
  DeclarationTest.suite,
  ExpressionTest.suite,
  ExpressionTestV2.suite,
  Formatter_DeclarationTest.suite,
  Formatter_ExpressionTest.suite,
  Formatter_ImportTest.suite,
  Formatter_JSXTest.suite,
  Formatter_ModuleTest.suite,
  FormatterTest.suite,
  IdentifierTest.suite,
  ImportTest.suite,
  JSXTest.suite,
  JSXTestV2.suite,
  NumberTest.suite,
  Primitive_BooleanTest.suite,
  Primitive_BooleanTestV2.suite,
  Primitive_NilTest.suite,
  Primitive_NilTestV2.suite,
  Primitive_StringTest.suite,
  Primitive_StringTestV2.suite,
  ProgramTest.suite,
  StatementTest.suite,
  TypingTest.suite,
];
