name: Build, Test and Release

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Make Stuff
        run: |
          touch SOME_FILE
          touch "${GITHUB_WORKSPACE}/OTHER_FILE"
          touch "/home/runner/work/LAST_FILE"

  test_compiler:
    name: Build and Test Compiler
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      # - name: Setup Node
      #   uses: actions/setup-node@v1

      - name: Test
        run: |
          echo ${GITHUB_WORKSPACE}
          ls -al ${GITHUB_WORKSPACE}
          ls -al /home/runner/work
          ls -al /home/runner/work/_temp
          ls -al /home/runner/work/_temp/_github_workflow
          ls -al /home/runner/work/knot
  #     - name: Install OCaml Dependencies
  #       run: esy install && esy pesy
  #       working-directory: compiler
  #     - name: Build Compiler
  #       run: esy build
  #       working-directory: compiler
  #     - name: Run Tests
  #       run: yarn test
  # test_packages:
  #   name: Build and Test Packages
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Setup Node
  #       uses: actions/setup-node@v1
  #     - name: Setup Yarn
  #       run: npm install -g yarn
  #     - name: Install Node Dependencies
  #       run: yarn install
  #     - name: Build Packages
  #       run: yarn build
  #     - name: Run Tests
  #       run: yarn test
  # test_webpack_react:
  #   name: Test Knot + React + Webpack
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v1
  #     - name: Setup Node
  #       uses: actions/checkout@v1
